<a href="https://colab.research.google.com/github/Faizal-syardi/Tugas-DataMining/blob/master/Decisiontree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets
import matplotlib.pyplot as plt

In [19]:
iris = datasets.load_iris()
features = iris['data']
target = iris['target']
print(features)
len(features)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

150

In [20]:
decisiontree = DecisionTreeClassifier(random_state=0,
                                      max_depth=None,min_samples_split=2,
                                      min_samples_leaf=1,min_weight_fraction_leaf=0,
                                      max_leaf_nodes=None,min_impurity_decrease=0)

In [21]:
model = decisiontree.fit(features,target)

In [22]:
observation = [[5, 4, 3, 2]]
model.predict(observation)
model.predict_proba(observation)

array([[0., 1., 0.]])

In [24]:
import numpy as np
import pandas as pd
from sklearn import tree

In [29]:
import pydotplus
from sklearn import tree
dot_data = tree.export_graphviz(decisiontree, out_file=None,feature_names=iris['feature_names'],class_names=iris['target_names'])
from IPython.display import Image
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())
graph.write_png("D:\irish.png")

True

In [25]:
irisDataset = pd.read_csv('Dtree.csv',delimiter=',',header=0)
irisDataset["Jenis"] = pd.factorize(irisDataset.Jenis)[0]
irisDataset = irisDataset.drop(labels = "Id",axis=1)
irisDataset = irisDataset.to_numpy()
print(irisDataset)

[[7.   3.02 4.02 1.02 0.  ]
 [6.05 2.08 4.02 1.03 0.  ]
 [6.03 2.08 4.02 1.04 0.  ]
 [4.09 2.07 4.03 1.04 0.  ]
 [6.06 3.03 3.   1.07 0.  ]
 [5.02 3.02 4.01 1.05 0.  ]
 [5.   2.08 6.   1.   0.  ]
 [5.09 3.   5.01 1.01 0.  ]
 [6.   2.08 5.09 1.   0.  ]
 [6.01 3.   5.06 1.02 0.  ]
 [5.06 2.08 5.08 1.06 0.  ]
 [6.07 3.08 6.06 1.05 0.  ]
 [5.06 2.08 4.05 1.06 0.  ]
 [5.08 2.08 6.03 1.05 0.  ]
 [5.07 3.08 5.08 1.03 1.  ]
 [5.05 2.08 6.01 1.03 1.  ]
 [5.05 3.02 5.01 1.03 1.  ]
 [5.08 3.02 5.03 1.02 1.  ]
 [6.   3.01 5.05 1.04 1.  ]
 [5.04 2.03 5.   1.02 1.  ]
 [6.   2.08 5.01 1.   1.  ]
 [6.07 2.08 5.03 1.03 1.  ]
 [6.03 3.03 5.05 1.05 0.  ]
 [5.06 2.04 6.07 1.04 0.  ]
 [5.05 2.09 6.09 1.05 0.  ]
 [5.05 2.07 5.   1.05 1.  ]
 [6.01 2.   5.07 1.03 1.  ]
 [5.08 3.   4.09 1.05 1.  ]
 [5.   2.02 5.01 1.03 1.  ]
 [5.06 2.09 5.03 1.06 0.  ]
 [6.07 2.09 4.07 1.   0.  ]
 [5.06 3.01 4.05 1.03 0.  ]
 [5.08 3.   4.09 1.04 0.  ]
 [6.02 2.07 4.   1.   1.  ]
 [5.06 2.02 4.06 1.05 1.  ]
 [5.09 2.05 4.05 1. 

In [26]:
dataTraining = np.concatenate((irisDataset[0:40,:],
                               irisDataset[50:90,:]), axis=0)
dataTesting = np.concatenate((irisDataset[40:50,:],
                              irisDataset[90:100,:]), axis=0)
inputTraining = dataTraining[:,0:4]
inputTesting = dataTesting[:,0:4]
labelTraining = dataTraining[:,4]
labelTesting = dataTesting[:,4]
print(labelTesting)
print(labelTraining)

[0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.
 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0.
 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.
 0. 0. 0. 0. 0. 0. 1. 1.]


In [27]:
model = tree.DecisionTreeClassifier()
model = model.fit(inputTraining, labelTraining)
hasilPrediksi = model.predict(inputTesting)
print("label sebenarnya: ", labelTesting)
print("hasil salah: ", hasilPrediksi)
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("prediksi benar: ", prediksiBenar, "data")
print("prediksi salah: ", prediksiSalah, "data")
print("akurasi: ", prediksiBenar/(prediksiBenar+prediksiSalah)*100,"%")

label sebenarnya:  [0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
hasil salah:  [0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
prediksi benar:  6 data
prediksi salah:  14 data
akurasi:  30.0 %
